version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    deploy:
      resources:
        limits:
          memory: 100M

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=fsmnza
      - DOCKER_INFLUXDB_INIT_PASSWORD=IotVladMalika
      - DOCKER_INFLUXDB_INIT_ORG=traffic
      - DOCKER_INFLUXDB_INIT_BUCKET=traffic_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-admin-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    deploy:
      resources:
        limits:
          memory: 500M

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - mqtt-broker
      - influxdb
    deploy:
      resources:
        limits:
          memory: 300M

volumes:
  influxdb-data: